"""Add strategy_tags and strategy_score to StockData

Revision ID: 1906d9795c13
Revises: 8ea510968c95
Create Date: 2025-03-21 16:22:59.859471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1906d9795c13'
down_revision = '8ea510968c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_tags', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('strategy_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_column('strategy_score')
        batch_op.drop_column('strategy_tags')

    # ### end Alembic commands ###
