"""Add strategy_label

Revision ID: 46a4228ec635
Revises: 1906d9795c13
Create Date: 2025-03-21 18:27:40.557440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a4228ec635'
down_revision = '1906d9795c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_column('strategy_label')

    # ### end Alembic commands ###
