"""Add stripe_customer_id and subscription_status to User model

Revision ID: 627e1d3d0473
Revises: 
Create Date: 2025-03-12 09:55:42.275559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627e1d3d0473'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_stripe_customer_id', ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stripe_customer_id', type_='unique')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
