"""Merged StockSummary into StockData

Revision ID: 8ea510968c95
Revises: 
Create Date: 2025-03-19 13:29:46.246639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ea510968c95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_summary')
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('summary_text')

    op.create_table('stock_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stock_symbol'], ['stock_data.symbol'], name='stock_summary_stock_symbol_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_summary_pkey'),
    sa.UniqueConstraint('stock_symbol', name='stock_summary_stock_symbol_key')
    )
    # ### end Alembic commands ###
