"""Add summary_last_updated to StockData

Revision ID: 93fdefaedaf1
Revises: 78ce3a107806
Create Date: 2025-03-27 11:57:07.396545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fdefaedaf1'
down_revision = '78ce3a107806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_column('summary_last_updated')

    # ### end Alembic commands ###
