"""Add days_in_a_row to StockData

Revision ID: b9dac4fc5f38
Revises: 46a4228ec635
Create Date: 2025-03-21 18:40:15.835319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dac4fc5f38'
down_revision = '46a4228ec635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_in_a_row', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_column('days_in_a_row')

    # ### end Alembic commands ###
