"""Add confidence_score to StockData

Revision ID: c841abc6522c
Revises: b9dac4fc5f38
Create Date: 2025-03-21 19:51:52.982278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c841abc6522c'
down_revision = 'b9dac4fc5f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_column('confidence_score')

    # ### end Alembic commands ###
